imu_static_transform_publisher:
  ros__parameters:
    x: '0.071406'
    y: '0'
    z: '-0.0033096'
    roll: '3.14159265359'
    pitch: '0'
    yaw: '0'
    parent_frame_id: base_link
    child_frame_id: imu_link
