serial_interface_node:
  ros__parameters:
    QP_TO_BYTE_STEER_SCALE: 22
    QP_TO_BYTE_STEER_OFFSET: 127
    QPPS_TO_BYTE_DRIVE_SCALE: 25
    QPPS_TO_BYTE_DRIVE_OFFSET: 127
    QP_TO_BYTE_TOOL_SCALE: 129 # Should match tool scale in Arduino code
    QP_TO_BYTE_TOOL_OFFSET: 0 
    QP_TO_BYTE_DELTA_POS_SCALE: 10
    QP_TO_BYTE_DELTA_POS_OFFSET: 127
